[package]
name = "fmby"
version = "0.1.0"
edition = "2024"
description = "A remake of fmhy/bot"
repository = "https://github.com/fmhy/fmby"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
anyhow = "1.0.104"
dotenvy = "0.15.7"
feed-rs = "2.4.0"
futures = "0.3.33"
image = { version = "0.25.10", default-features = false, features = ["png"] }
poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next", default-features = false, features = [
  "cache",
  "chrono",
  "handle_panics",
] }
pulldown-cmark = { version = "0.13.4", default-features = false }
rand = "0.10.2"
regex = "1.13.1"
reqwest = { version = "0.13.4", default-features = false, features = [
  "json",
  "rustls-no-provider",
] }
rustls = { version = "0.23.43", default-features = false, features = ["ring"] }
sea-orm = { version = "2.0.1", default-features = false, features = [
  "macros",
  "runtime-tokio-rustls",
  "sqlx-postgres",
  "with-chrono",
  "with-json",
  "with-uuid",
] }
sea-orm-migration = "2.0.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next", default-features = false, features = [
  "builder",
  "gateway",
  "model",
  "utils",
  "collector",
  "framework",
  "rustls_backend_no_provider",
] }
thiserror = "2"
tokio = { version = "1.53.1", features = [
  "macros",
  "rt-multi-thread",
  "signal",
] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url = "2.5.8"
wordcloud-rs = { version = "0.1.17", default-features = false }

[patch.crates-io]
wordcloud-rs = { git = "https://github.com/exefer/wordcloud-rs" }

[profile.release]
opt-level = "s"
strip = true
lto = true
panic = "abort"
codegen-units = 1
