[package]
name = "fmby"
version = "0.1.0"
edition = "2024"
authors = ["Exefer"]
repository = "https://github.com/exefer/fmby"
description = "A remake of FMHY/bot"
readme = "README.md"
publish = false

[workspace]
members = ["migration", "entity", "fmby_core", "fmby_commands"]

[dependencies]
serde.workspace = true
tokio.workspace = true
sea-orm.workspace = true
anyhow.workspace = true
poise.workspace = true
migration = { path = "migration" }
entity = { path = "entity" }
fmby_core = { path = "fmby_core" }
fmby_commands = { path = "fmby_commands" }
dotenvy = "0.15.7"
tracing = "0.1.41"
serde_json = "1.0.142"
regex = "1.11.1"
reqwest = "0.12.23"
pulldown-cmark = "0.13.0"

[workspace.dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
sea-orm = { version = "1.1.0", default-features = false, features = [
    "sqlx-postgres",
    "runtime-tokio",
    "with-json",
] }
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.99"

[patch.'https://github.com/serenity-rs/serenity']
serenity = { git = 'https://github.com/jamesbt365/serenity', branch = 'components-v2-withtag-gradient-nameplates/decor-resolved' }

[workspace.dependencies.poise]
git = "https://github.com/serenity-rs/poise"
features = ["cache"]
branch = "serenity-next"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
