[package]
name = "fmby_entities"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "fmby_entities"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
sea-orm = { workspace = true }
