//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub use super::rss_feed_entries::Entity as RssFeedEntries;
pub use super::rss_feeds::Entity as RssFeeds;
pub use super::wiki_urls::Entity as WikiUrls;
