//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "rss_feed_status")]
pub enum RssFeedStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "wiki_url_status")]
pub enum WikiUrlStatus {
    #[sea_orm(string_value = "added")]
    Added,
    #[sea_orm(string_value = "removed")]
    Removed,
    #[sea_orm(string_value = "pending")]
    Pending,
}
