//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "wiki_url_status")]
pub enum WikiUrlStatus {
    #[sea_orm(string_value = "added")]
    Added,
    #[sea_orm(string_value = "rejected")]
    Removed,
    #[sea_orm(string_value = "pending")]
    Pending,
}
